name: Update Leaderboard
on:
  issues:
    types: [opened]  # 当有新 Issue 时触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 拉取代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Update leaderboard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动注入的 Token
        run: python scripts/update_leaderboard.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add docs/leaderboard.json
          git commit -m "Auto-update leaderboard"
          git push